 
### Site metadata ###

site_name: SosoTech Documentation
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://github.com/sosotechnologies/soso-docs/

repo_url: https://github.com/sosotechnologies/soso-docs
edit_uri: edit/master/soso-docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About SosoTech: about-sosotech.md
  - Tutorial:
      - GitOps: tutorial/gitops.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
